
app: 
  datasource: 
    jdbcUrl: jdbc:h2:~/extracts-webservice;AUTO_SERVER=TRUE
    username: sa
    password: 

server: 
  port: 8090

chainrpc: 
  host: localhost
  port: 2910
  chainName: registryv3
  username: multichainrpc
  password: AqvnFYJaLsfMe9A9TDHeoHfgDncPppqJGai52yZtvoP
  mode: REGISTER
  multichainCli: /home/jboss/extracts-poc/multichain-1.0-beta-1/multichain-cli
  multichainD: /home/jboss/extracts-poc/multichain-1.0-beta-1/multichaind
  multichainUtil: /home/jboss/extracts-poc/multichain-1.0-beta-1/multichain-util
  publicKey : 16SwYKazYw2sonfFmFSEQCfyoc6b6Gsjeo5VGY

remote: 
  datasource: 
    jdbcUrl: jdbc:oracle:thin:@192.168.32.51:1521:xe
    username: CSD
    password: CSD
